mysql:
  image: zhouxing/mysql:5.5
  ports:
    - '3306:3306'
app:
  build: .
  command: bundle exec rake db:create & rake db:migrate & unicorn_rails -c config/unicorn.rb -E production -p 8080
  volumes:
    - .:/app
  ports:
    - '8080:8080'
  links:
    - mysql
