mysql: &mysql
  adapter: mysql2
  username: root
  password:
  database: xingishere_<%= Rails.env %>

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  encoding: utf8

  <<: *<%= ENV['DB'] || "mysql" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
