author_name: 'XX'
domain_name: 'http://www.xxx.com'
publish_status:
  deleted:  0
  published:  1
regexp:
  email: \A([a-zA-Z0-9_-])+@(([a-zA-Z0-9_-])+)((\.([a-zA-Z0-9_-])+)*)((\.[a-zA-Z0-9_-]{2,3}){1,2})\z
  qq: \A[1-9]*[1-9][0-9]*\z
  url_name: \A\w+_\d+\z
  phone_number: /\A(?:130|131|132|133|134|135|136|137|138|139|145|147|150|151|152|153|155|156|157|158|159|170|180|181|182|183|184|185|186|187|188|189)[0-9]{8}\z/

secret_token: 'wefg4Xdfeio3eir9t0g1okl28eifud7y6'
omniauth:
  key: 'xxxxxxxxxx'
  secret: 'xxxxxxxxxxx'
ga_track_id: 'UA-XXXXXXXX-X'
